spring:
  application:
    name: waguwagu-payment
  datasource:
    url: jdbc:mysql://waguwagu-payment-mysql:3306/waguwagu_payment?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: {MYSQL_USER}
    password: {MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: 34.71.194.186:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-prod
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: "*"