spring:
  application:
    name: waguwagu-payment
  datasource:
    url: jdbc:mysql://localhost:3306/waguwagu_payment?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: 34.71.194.186:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-local
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: "*"
kafka:
  delivery-topic:
    name: delivery-income-topic
  store-topic:
    name: store-income-topic